### ISSUE TITLE
Faltando sons

### ISSUE THREAD

**Issue by humbertobz** [Doriedson/mario-shellscript#1]
Por favor adicione ao git os sons que estão definidos no fonte.

worldcleared.ogg, flagpole.ogg, timewarning.ogg, gameover.ogg, die.ogg, world1-1.ogg, jump.ogg, brick.ogg, coin.ogg, up.ogg, stomp.ogg

**Comment by Doriedson** [comment]
Não havia colocado os sons por que não sei quem é o autor. Mas, agora, coloquei assim mesmo já que muitos me pediram.
