### ISSUE TITLE
erro ao rodar mario.sh

### ISSUE THREAD

**Issue by radaway** [Doriedson/mario-shellscript#2]
mario.sh: linha 293: erro de sintaxe próximo do `token' não esperado `newline'
mario.sh: linha 293: `		done'

**Comment by Doriedson** [comment]
Eu desenvolvi em Ubuntu 12, pode ser quem em outras distribuições haja alguma diferença apesar de ter sido desenvolvido com comandos básicos em Shell Script

**Comment by Doriedson** [comment]
Ok, thanks!
